-- Insert distinct airport data into DIM_DATE
INSERT INTO "DIM_DATE"
SELECT DISTINCT
    TO_DATE("FLIGHTDATE", 'YYYY-MM-DD'),
    YEAR(TO_DATE("FLIGHTDATE", 'YYYY-MM-DD')) AS "YEAR",
    MONTH(TO_DATE("FLIGHTDATE", 'YYYY-MM-DD')) AS "MONTH",
    DAY(TO_DATE("FLIGHTDATE", 'YYYY-MM-DD')) AS "DAY",
    DAYNAME(TO_DATE("FLIGHTDATE", 'YYYY-MM-DD')) AS "WEEKDAY"
FROM "FACT_FLIGHTS"
WHERE "FLIGHTDATE" IS NOT NULL;
