---------------
-- Insert distinct airport data into DIM_AIRPORT
INSERT INTO "DIM_AIRPORT"
SELECT DISTINCT
    "ORIGINAIRPORTCODE",
    TRIM(SPLIT_PART("ORIGINAIRPORTNAME", ': ', 2)) AS "AIRPORTNAME",
    "ORIGINCITYNAME",
    "ORIGINSTATE",
    "ORIGINSTATENAME"
FROM "FACT_FLIGHTS"
UNION
SELECT DISTINCT
    "DESTAIRPORTCODE",
    TRIM(SPLIT_PART("DESTAIRPORTNAME", ': ', 2)) AS "AIRPORTNAME",
    "DESTCITYNAME",
    "DESTSTATE",
    "DESTSTATENAME"
FROM "FACT_FLIGHTS";
