---------------
-- Insert distinct airline data into DIM_AIRLINE
INSERT INTO DIM_AIRLINE (AIRLINECODE, AIRLINENAME)
SELECT DISTINCT 
    AIRLINECODE,     
    TRIM(REGEXP_REPLACE(AIRLINENAME, ':.*', '')) AS AIRLINENAME
FROM FACT_FLIGHTS;
