---------------
// CREATE DIM_AIRPORT
CREATE OR REPLACE TABLE "DIM_AIRPORT" (
    "AIRPORTCODE" STRING PRIMARY KEY,
    "AIRPORTNAME" STRING,
    "CITYNAME" STRING,
    "STATE" STRING,
    "STATENAME" STRING
);


