---------------
--\\3. Create and load appropriate dimension table(s) named DIM_*.
//CREATING DIMENSION TABLES
// CREATE DIM_AIRLINE
CREATE OR REPLACE TABLE DIM_AIRLINE (
    AIRLINECODE VARCHAR PRIMARY KEY,
    AIRLINENAME VARCHAR
);

---------------
-- Insert distinct airline data into DIM_AIRLINE
INSERT INTO DIM_AIRLINE (AIRLINECODE, AIRLINENAME)
SELECT DISTINCT 
    AIRLINECODE,     
    TRIM(REGEXP_REPLACE(AIRLINENAME, ':.*', '')) AS AIRLINENAME
FROM FACT_FLIGHTS;
