---------------
--\\3. Create and load appropriate dimension table(s) named DIM_*.
//CREATING DIMENSION TABLES
// CREATE DIM_AIRLINE
CREATE OR REPLACE TABLE DIM_AIRLINE (
    AIRLINECODE VARCHAR PRIMARY KEY,
    AIRLINENAME VARCHAR
);


